// Filepath: src/components/OnboardingFlow.tsx
// Author: Robert Kirkpatrick
// Generated by: Venice AI
// v1.0.2 - Replaced nostr-tools.utils.hexToBytes with a local implementation to fix compilation errors.

import React, { useState, useEffect } from 'react';
import * as nostrTools from 'nostr-tools';
import './App.css'; // Reuse App.css for basic styling

// Define the steps of the onboarding process
enum SetupStep {
  INITIAL_PROMPT = 'initial_prompt',
  KEY_GENERATION = 'key_generation',
  LOCATION_PERMISSION = 'location_permission',
}

interface OnboardingFlowProps {
  onComplete: (publicKey: string) => void;
}

/**
 * Converts a Uint8Array to a hexadecimal string.
 * This is a helper function to avoid potential issues with nostr-tools.
 * @param {Uint8Array} bytes - The byte array to convert.
 * @returns {string} The resulting hexadecimal string.
 */
const bytesToHex = (bytes: Uint8Array): string => {
  return Array.from(bytes, byte => byte.toString(16).padStart(2, '0')).join('');
};

/**
 * Converts a hexadecimal string to a Uint8Array.
 * This replaces nostrTools.utils.hexToBytes to avoid potential compilation issues.
 * @param {string} hex - The hexadecimal string to convert.
 * @returns {Uint8Array} The resulting byte array.
 */
const hexToBytes = (hex: string): Uint8Array => {
  const bytes = new Uint8Array(hex.length / 2);
  for (let i = 0; i < bytes.length; i++) {
    bytes[i] = parseInt(hex.substr(i * 2, 2), 16);
  }
  return bytes;
};

const OnboardingFlow: React.FC<OnboardingFlowProps> = ({ onComplete }) => {
  const [setupStep, setSetupStep] = useState<SetupStep>(SetupStep.INITIAL_PROMPT);

  const handleLocationResponse = (granted: boolean) => {
    // For now, we don't need to store the location.
    // The app will ask for it later if needed.
    // The onboarding flow is now complete.
    const storedPrivateKey = localStorage.getItem('agora_privateKey');
    if (storedPrivateKey) {
      try {
        // Use the local hexToBytes helper function
        const pubkeyUint8Array = nostrTools.getPublicKey(hexToBytes(storedPrivateKey));
        const publicKeyHex = bytesToHex(pubkeyUint8Array);
        onComplete(publicKeyHex);
      } catch (error) {
        console.error("Could not retrieve public key after onboarding:", error);
        alert('A critical error occurred. Please refresh the page.');
      }
    } else {
      // This should not happen, but it's a safeguard
      alert('Setup failed. Please try again.');
    }
  };
  
  const handleSkipLocation = () => {
    handleLocationResponse(false);
  };

  useEffect(() => {
    // This effect will trigger when the component moves to the key generation step
    if (setupStep === SetupStep.KEY_GENERATION) {
      // Simulate a short delay to show the spinner
      const timer = setTimeout(() => {
        try {
          // 1. Silent Key Generation
          const privateKeyUint8Array = crypto.getRandomValues(new Uint8Array(32));
          const privateKeyHex = bytesToHex(privateKeyUint8Array);
          const pubkeyUint8Array = nostrTools.getPublicKey(privateKeyUint8Array);
          const publicKeyHex = bytesToHex(pubkeyUint8Array);

          // 2. Store the new key pair in localStorage
          localStorage.setItem('agora_privateKey', privateKeyHex);
          console.log('New user identity created. Public Key:', publicKeyHex);

          // 3. Move to the next step: Location Permission
          setSetupStep(SetupStep.LOCATION_PERMISSION);
        } catch (error) {
          console.error("Failed to generate new identity during onboarding:", error);
          // In a real app, you might show an error message and a "Retry" button
          alert('An error occurred during setup. Please refresh and try again.');
        }
      }, 2000); // 2-second delay for the spinner

      // Cleanup the timer if the component unmounts
      return () => clearTimeout(timer);
    }
  }, [setupStep]);

  const handleStart = () => {
    setSetupStep(SetupStep.KEY_GENERATION);
  };

  const renderStep = () => {
    switch (setupStep) {
      case SetupStep.INITIAL_PROMPT:
        return (
          <div className="onboarding-container">
            <h2>Welcome to Agora Marketplace</h2>
            <p>A decentralized platform for discovering, creating, and sharing real-world events and gatherings.</p>
            <button onClick={handleStart} className="primary-button">
              Tap to start using Agora Marketplace
            </button>
          </div>
        );

      case SetupStep.KEY_GENERATION:
        return (
          <div className="onboarding-container">
            <div className="spinner"></div>
            <p>Setting things up…</p>
          </div>
        );

      case SetupStep.LOCATION_PERMISSION:
        return (
          <div className="onboarding-container">
            <h2>Almost there!</h2>
            <p>Can we see your location to show nearby events?</p>
            <div className="location-buttons">
              <button onClick={() => handleLocationResponse(true)} className="primary-button">
                Allow
              </button>
              <button onClick={handleSkipLocation} className="secondary-button">
                Not now
              </button>
            </div>
          </div>
        );

      default:
        return null; // Should not be reached
    }
  };

  return <main>{renderStep()}</main>;
};

export default OnboardingFlow;
// --- End of File ---
// Filepath: src/components/OnboardingFlow.tsx
// Version: v1.0.2
