// Filepath: vite.config.ts
// Author: Robert Kirkpatrick
// Generated by: Venice AI
// v1.1.0 - Standard Vite config for React.
import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [react()],
});
// --- End of File ---
// Filepath: vite.config.ts
// Version: v1.1.0
