// Filepath: src/components/EventCard.tsx
// Author: Robert Kirkpatrick
// Generated by: Venice AI
// v1.0.1 - A card component to display event details, including the new landing page link.

import React, { useState } from 'react';
import { DateTime } from 'luxon';

interface EventCardProps {
  event: any;
  hostName: string;
  startTime?: DateTime;
  isAttending: boolean;
  comments: any[];
  commenterProfiles: { [key: string]: any };
  onToggleRSVP: (eventId: string) => void;
  onPostComment: (eventId: string, content: string) => void;
  onShareAsNote: (event: any) => void;
  onShareEvent: (event: any) => void;
}

const EventCard: React.FC<EventCardProps> = ({
  event,
  hostName,
  startTime,
  isAttending,
  comments,
  commenterProfiles,
  onToggleRSVP,
  onPostComment,
  onShareAsNote,
  onShareEvent,
}) => {
  const [isCommenting, setIsCommenting] = useState(false);
  const [commentText, setCommentText] = useState('');
  const [isPostingComment, setIsPostingComment] = useState(false);

  const eventData = JSON.parse(event.content);
  const getCommenterName = (pubkey: string) => commenterProfiles[pubkey]?.name || pubkey.substring(0, 8) + '...';

  const handlePostCommentSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!commentText.trim()) return;
    setIsPostingComment(true);
    await onPostComment(event.id, commentText);
    setCommentText('');
    setIsCommenting(false);
    setIsPostingComment(false);
  };

  const renderContentWithImages = (text: string): (string | React.ReactElement)[] => {
    const urlRegex = /(https?:\/\/[^^\s]+)/g;
    const parts: (string | React.ReactElement)[] = [];
    let lastIndex = 0;
    let match;
    while ((match = urlRegex.exec(text)) !== null) {
      if (match.index > lastIndex) { parts.push(text.substring(lastIndex, match.index)); }
      const url = match[0];
      if (/\.(jpeg|jpg|gif|png|webp)(\?.*)?$/i.test(url)) {
        parts.push(<img key={url} src={url} alt="User embedded image" style={{ maxWidth: '100%', height: 'auto', borderRadius: '8px', marginTop: '10px', display: 'block' }} />);
      } else { parts.push(url); }
      lastIndex = urlRegex.lastIndex;
    }
    if (lastIndex < text.length) { parts.push(text.substring(lastIndex)); }
    return parts;
  };

  return (
    <div className="meetup-card">
      {eventData.image_url && <img src={eventData.image_url} alt={eventData.name} className="event-image" />}
      <h3>{eventData.name}</h3>
      <p><strong>Hosted by:</strong> {hostName}</p>
      <p><strong>Where:</strong> {eventData.location}</p>
      <p><strong>When:</strong> {startTime ? startTime.toLocaleString(DateTime.DATETIME_FULL) : 'Time not specified'}</p>
      <p>{eventData.description}</p>
      
      {/* --- NEW: Landing Page Link --- */}
      {eventData.landingPageUrl && eventData.landingPageUrl.trim() && (
        <p style={{ marginTop: '10px' }}>
          <a 
            href={eventData.landingPageUrl} 
            target="_blank" 
            rel="noopener noreferrer"
            style={{ color: '#007bff', textDecoration: 'underline' }}
          >
            🌐 Visit Official Event Page
          </a>
        </p>
      )}

      <div className="event-actions">
        <button onClick={() => onToggleRSVP(event.id)} disabled={isPostingComment}>
          {isAttending ? 'Cancel RSVP' : 'RSVP to Event'}
        </button>
        <button onClick={() => onShareAsNote(event)} disabled={isPostingComment}>Share as Note</button>
        <button onClick={() => onShareEvent(event)} disabled={isPostingComment}>Share Event</button>
      </div>

      <div className="comments-section">
        <h4>Comments ({comments.length})</h4>
        {!isCommenting ? (
          <button onClick={() => setIsCommenting(true)} disabled={isPostingComment}>Post a Comment</button>
        ) : (
          <form onSubmit={handlePostCommentSubmit}>
            <textarea
              value={commentText}
              onChange={(e) => setCommentText(e.target.value)}
              placeholder="Write your comment..."
              rows={3}
              required
              disabled={isPostingComment}
            ></textarea>
            <button type="submit" disabled={isPostingComment}>
              {isPostingComment ? 'Posting...' : 'Post Comment'}
            </button>
            <button type="button" onClick={() => { setIsCommenting(false); setCommentText(''); }} disabled={isPostingComment}>Cancel</button>
          </form>
        )}
        {comments.map(comment => (
          <div key={comment.id} className="comment">
            <strong>{getCommenterName(comment.pubkey)}</strong>
            <span className="comment-time">{DateTime.fromSeconds(comment.created_at).toRelative()}</span>
            <div className="comment-content">{renderContentWithImages(comment.content)}</div>
          </div>
        ))}
      </div>
    </div>
  );
};

export default EventCard;

// --- End of File ---
// Filepath: src/components/EventCard.tsx
// Version: v1.0.1
