// Filepath: src/components/EventForm.tsx
// Author: Robert Kirkpatrick
// Generated by: Venice AI
// v1.0.0 - A reusable form component for creating new events.

import React, { useState } from 'react';

interface EventFormProps {
  onSubmit: (e: React.FormEvent, eventData: any) => Promise<void>;
}

const EventForm: React.FC<EventFormProps> = ({ onSubmit }) => {
  const [newEvent, setNewEvent] = useState({
    name: '',
    location: '',
    startTime: '',
    description: '',
    image_url: '',
    landingPageUrl: '',
  });

  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => {
    const { name, value } = e.target;
    setNewEvent(prev => ({ ...prev, [name]: value }));
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!newEvent.name || !newEvent.location || !newEvent.startTime) {
      alert('Please fill in the Name, Location, and Start Time.');
      return;
    }
    await onSubmit(e, newEvent);
  };

  return (
    <form onSubmit={handleSubmit} className="event-form" style={{ marginBottom: '40px', padding: '20px', border: '1px solid #ccc', borderRadius: '8px' }}>
      <h3>Create a New Event</h3>
      <label>
        Event Name:
        <input type="text" name="name" value={newEvent.name} onChange={handleInputChange} required />
      </label>
      <label>
        Location:
        <input type="text" name="location" value={newEvent.location} onChange={handleInputChange} required />
      </label>
      <label>
        Start Time:
        <input type="datetime-local" name="startTime" value={newEvent.startTime} onChange={handleInputChange} required />
      </label>
      <label>
        Description:
        <textarea name="description" value={newEvent.description} onChange={handleInputChange} rows={4}></textarea>
      </label>
      <label>
        Image URL (Optional):
        <input type="url" name="image_url" value={newEvent.image_url} onChange={handleInputChange} placeholder="https://example.com/image.jpg" />
      </label>
      <label>
        Event Landing Page (Optional):
        <input
          type="url"
          name="landingPageUrl"
          value={newEvent.landingPageUrl || ''}
          onChange={handleInputChange}
          placeholder="https://example.com/my-event-page"
        />
      </label>
      <button type="submit">Create Event</button>
    </form>
  );
};

export default EventForm;

// --- End of File ---
// Filepath: src/components/EventForm.tsx
// Version: v1.0.0
