// Filepath: src/components/SingleEventView.tsx
// Author: Robert Kirkpatrick
// Generated by: Venice AI
// v1.0.1 - A component to display a single event page.

import React, { useState, useEffect } from 'react';
import { useParams, useNavigate, Link } from 'react-router-dom';
import { DateTime } from 'luxon';

// NOTE: This component is a simplified version for demonstration.
// It fetches data from a single relay and does not include all features like RSVPs or posting comments.

const SingleEventView: React.FC = () => {
    const { eventId } = useParams<{ eventId: string }>();
    const navigate = useNavigate();
    const [event, setEvent] = useState<any | null>(null);
    const [hostProfile, setHostProfile] = useState<any | null>(null);
    const [isLoading, setIsLoading] = useState(true);
    const [error, setError] = useState<string | null>(null);

    useEffect(() => {
        if (!eventId) {
            setError("No event ID provided.");
            setIsLoading(false);
            return;
        }

        // This is a simplified fetch for one event.
        // A more robust solution would query multiple relays.
        const fetchEvent = async () => {
            try {
                const response = await fetch(`https://relay.damus.io/${eventId}`);
                if (!response.ok) throw new Error('Event not found on relay.');
                const eventData = await response.json();
                if (eventData.id !== eventId) throw new Error('Mismatched event ID.');
                setEvent(eventData);
            } catch (err: any) {
                setError(err.message || "Failed to fetch event.");
            } finally {
                setIsLoading(false);
            }
        };

        fetchEvent();
    }, [eventId]);

    if (isLoading) return <p>Loading event...</p>;
    if (error) return <p>Error: {error}</p>;
    if (!event) return <p>Event not found.</p>;

    // This is a placeholder. A real app would fetch the profile.
    const getHostName = () => hostProfile?.name || event?.pubkey.substring(0, 8) + '...';
    
    const renderContentWithImages = (text: string): (string | React.ReactElement)[] => {
        const urlRegex = /(https?:\/\/[^^\s]+)/g;
        const parts: (string | React.ReactElement)[] = [];
        let lastIndex = 0;
        let match;
        while ((match = urlRegex.exec(text)) !== null) {
            if (match.index > lastIndex) { parts.push(text.substring(lastIndex, match.index)); }
            const url = match[0];
            if (/\.(jpeg|jpg|gif|png|webp)(\?.*)?$/i.test(url)) {
                parts.push(<img key={url} src={url} alt="User embedded image" style={{ maxWidth: '100%', height: 'auto', borderRadius: '8px', marginTop: '10px', display: 'block' }} />);
            } else { parts.push(url); }
            lastIndex = urlRegex.lastIndex;
        }
        if (lastIndex < text.length) { parts.push(text.substring(lastIndex)); }
        return parts;
    };

    const eventData = JSON.parse(event.content);
    const startTime = DateTime.fromISO(eventData.startTime);

    return (
        <div style={{ maxWidth: '800px', margin: '0 auto', padding: '20px' }}>
            <button onClick={() => navigate('/')} style={{ marginBottom: '20px', cursor: 'pointer' }}>&larr; Back to Events</button>
            <div className="meetup-card" style={{ padding: '20px' }}>
                {eventData.image_url && <img src={eventData.image_url} alt={eventData.name} className="event-image" />}
                <h1>{eventData.name}</h1>
                <p><strong>Hosted by:</strong> {getHostName()}</p>
                <p><strong>Where:</strong> {eventData.location}</p>
                <p><strong>When:</strong> {startTime.toLocaleString(DateTime.DATETIME_FULL)}</p>
                <p>{eventData.description}</p>
                {/* NOTE: RSVP and Comment sections are omitted for simplicity */}
            </div>
        </div>
    );
};

export default SingleEventView;
