// Filepath: src/App.tsx
// Author: Robert Kirkpatrick
// Generated by: Venice AI
// v1.0.1 - Updated to use React Router for navigation.

import React, { useState, useEffect } from 'react';
import { BrowserRouter as Router, Routes, Route } from 'react-router-dom';
import * as nostrTools from 'nostr-tools';
import HomePage from './HomePage';
import SingleEventView from './components/SingleEventView';
import './App.css';

function App() {
  const [userPublicKey, setUserPublicKey] = useState<string | null>(null);
  const [isLoggingIn, setIsLoggingIn] = useState(false);

  useEffect(() => {
    const storedPubkey = localStorage.getItem('agora_publicKey');
    if (storedPubkey) {
      setUserPublicKey(storedPubkey);
    } else {
      if (window.nostr) {
        window.nostr.getPublicKey().then(pubkey => {
          localStorage.setItem('agora_publicKey', pubkey);
          setUserPublicKey(pubkey);
        }).catch(err => {
          console.error("Could not get public key:", err);
        });
      }
    }
  }, []);

  const handleLogin = async () => {
    setIsLoggingIn(true);
    try {
      if (window.nostr) {
        const pubkey = await window.nostr.getPublicKey();
        localStorage.setItem('agora_publicKey', pubkey);
        setUserPublicKey(pubkey);
      } else {
        alert('Nostr extension not found. Please install a Nostr signer extension like NIP-07 or use a private key.');
      }
    } catch (error) {
      console.error("Login failed:", error);
      alert('Login failed. Please check your Nostr extension.');
    } finally {
      setIsLoggingIn(false);
    }
  };

  const handlePrivateKeyLogin = (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    const formData = new FormData(e.currentTarget);
    const privateKey = formData.get('privateKey') as string;
    try {
      const pubkey = nostrTools.getPublicKey(privateKey);
      localStorage.setItem('agora_publicKey', pubkey);
      localStorage.setItem('agora_privateKey', privateKey);
      setUserPublicKey(pubkey);
    } catch (error) {
      alert('Invalid Private Key. Please check and try again.');
    }
  };

  if (!userPublicKey) {
    return (
      <div style={{ padding: '20px', maxWidth: '400px', margin: '50px auto', border: '1px solid #ccc', borderRadius: '8px' }}>
        <h1>Welcome to Agora Marketplace</h1>
        <p>Please log in to create and interact with events.</p>
        <button onClick={handleLogin} disabled={isLoggingIn} style={{ width: '100%', padding: '10px', marginBottom: '10px', cursor: 'pointer' }}>
          {isLoggingIn ? 'Logging in...' : 'Login with Nostr Extension (NIP-07)'}
        </button>
        <p style={{ textAlign: 'center', color: '#666' }}>or</p>
        <form onSubmit={handlePrivateKeyLogin}>
          <input type="password" name="privateKey" placeholder="Enter your Private Key (nsec)" required style={{ width: '100%', padding: '10px', marginBottom: '10px' }} />
          <button type="submit" style={{ width: '100%', padding: '10px', cursor: 'pointer' }}>Login with Private Key</button>
        </form>
      </div>
    );
  }

  return (
    <Router>
      <div style={{ padding: '20px' }}>
        <header style={{ marginBottom: '20px' }}>
          <h1>Agora Marketplace</h1>
          <p>Logged in as: {userPublicKey.substring(0, 8)}...</p>
        </header>
        <main>
          <Routes>
            <Route path="/" element={<HomePage userPublicKey={userPublicKey} />} />
            <Route path="/e/:eventId" element={<SingleEventView />} />
          </Routes>
        </main>
      </div>
    </Router>
  );
}

export default App;
