// Filepath: src/App.tsx
// Author: Robert Kirkpatrick
// Generated by: Venice AI
// v1.0.11 - Fixed TypeScript build error for nostr-tools API.

import { useState, useEffect } from 'react';
import { BrowserRouter as Router, Routes, Route, Navigate } from 'react-router-dom';
import * as nostrTools from 'nostr-tools';
import HomePage from './HomePage';
import ProfilePage from './ProfilePage';
import SingleEventView from './components/SingleEventView';
import './App.css';

function App() {
  const [userPublicKey, setUserPublicKey] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    // Try to get pubkey from NIP-07 extension (like Alby or nos2x)
    if (window.nostr) {
      window.nostr.getPublicKey().then(pubkey => {
        setUserPublicKey(pubkey);
        setIsLoading(false);
      }).catch(err => {
        console.error("Could not get pubkey from extension:", err);
        // Fallback to localStorage if extension fails or is not present
        checkLocalStorage();
      });
    } else {
      // No extension found, check localStorage
      checkLocalStorage();
    }
  }, []);

  const checkLocalStorage = () => {
    const storedPrivateKey = localStorage.getItem('agora_privateKey');
    if (storedPrivateKey) {
      try {
        // FIX: Convert hex key to bytes for nostr-tools
        const pubkey = nostrTools.getPublicKey(nostrTools.utils.hexToBytes(storedPrivateKey));
        setUserPublicKey(pubkey);
        setIsLoading(false);
      } catch (error) {
        console.error("Invalid private key in localStorage:", error);
        localStorage.removeItem('agora_privateKey'); // Clean up invalid key
        setIsLoading(false);
      }
    } else {
      setIsLoading(false);
    }
  };

  const handleLogin = async () => {
    // Try NIP-07 extension first
    if (window.nostr) {
      try {
        const pubkey = await window.nostr.getPublicKey();
        setUserPublicKey(pubkey);
      } catch (err) {
        alert('Could not log in with Nostr extension.');
      }
    } else {
      const privateKey = prompt('Enter your private key (nsec or hex):');
      if (privateKey) {
        let hexKey = privateKey;
        if (privateKey.startsWith('nsec')) {
          hexKey = nostrTools.nip19.decode(privateKey).data as string;
        }
        try {
          // FIX: Convert hex key to bytes for nostr-tools
          const pubkey = nostrTools.getPublicKey(nostrTools.utils.hexToBytes(hexKey));
          localStorage.setItem('agora_privateKey', hexKey);
          setUserPublicKey(pubkey);
        } catch (error) {
          alert('Invalid private key format.');
        }
      }
    }
  };

  const handleLogout = () => {
    setUserPublicKey(null);
    localStorage.removeItem('agora_privateKey');
  };

  if (isLoading) {
    return <div>Loading...</div>;
  }

  return (
    <Router>
      <div className="App">
        <header className="App-header">
          <h1>Agora Marketplace</h1>
          {userPublicKey ? (
            <div className="user-info">
              <span>Logged in</span>
              <button onClick={handleLogout}>Logout</button>
            </div>
          ) : (
            <button onClick={handleLogin}>Login</button>
          )}
        </header>
        <main>
          <Routes>
            <Route path="/" element={userPublicKey ? <HomePage userPublicKey={userPublicKey} /> : <Navigate replace to="/login" />} />
            <Route path="/event/:eventId" element={userPublicKey ? <SingleEventView userPublicKey={userPublicKey} /> : <Navigate replace to="/login" />} />
            <Route path="/profile" element={userPublicKey ? <ProfilePage userPublicKey={userPublicKey} /> : <Navigate replace to="/login" />} />
            <Route path="/login" element={<div style={{ padding: '20px', textAlign: 'center' }}><h2>Login Required</h2><p>Please log in to view the Agora Marketplace.</p><button onClick={handleLogin}>Login</button></div>} />
          </Routes>
        </main>
      </div>
    </Router>
  );
}

export default App;

// --- End of File ---
// Filepath: src/App.tsx
// Version: v1.0.11
