// Filepath: src/App.tsx
// Author: Robert Kirkpatrick
// Generated by: Venice AI
// v11.0.1 - Updated routing to use LoginPage as the entry point

import React, { useEffect, useState } from 'react';
import { BrowserRouter as Router, Routes, Route, Link, Navigate } from 'react-router-dom';
import HomePage from './HomePage';
import ProfilePage from './ProfilePage';
import LoginPage from './LoginPage';

// Define the NIP-07 interface for TypeScript
declare global {
  interface Window {
    nostr?: {
      getPublicKey(): Promise<string>;
      signEvent(event: any): Promise<any>;
    };
  }
}

// --- Main App Component with Authentication Logic ---
const App: React.FC = () => {
  const [userPublicKey, setUserPublicKey] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    // Check for in-app keys first
    const storedPublicKey = localStorage.getItem('agora_publicKey');
    if (storedPublicKey) {
      setUserPublicKey(storedPublicKey);
      setIsLoading(false);
      return;
    }

    // Fallback to NIP-07 extension
    if (window.nostr) {
      window.nostr.getPublicKey().then(pubkey => {
        setUserPublicKey(pubkey);
        setIsLoading(false);
      }).catch(() => {
        // Extension exists but user denied, treat as logged out
        setIsLoading(false);
      });
    } else {
      // No extension and no in-app key
      setIsLoading(false);
    }
  }, []);

  if (isLoading) {
    return <div>Loading Agora...</div>;
  }

  if (!userPublicKey) {
    // User is not logged in, show the login page
    return (
      <Router>
        <Routes>
          <Route path="/login" element={<LoginPage />} />
          <Route path="*" element={<Navigate to="/login" replace />} />
        </Routes>
      </Router>
    );
  }

  // User is logged in, show the main app
  return (
    <Router>
      <div style={{ fontFamily: 'sans-serif', padding: '20px', maxWidth: '1200px', margin: '0 auto' }}>
        <header style={{ borderBottom: '2px solid #eee', paddingBottom: '20px', marginBottom: '20px' }}>
          <h1>Agora Marketplace App</h1>
          <nav>
            <Link to="/" style={{ marginRight: '15px', textDecoration: 'none', color: '#007bff' }}>Events</Link>
            <Link to="/profile" style={{ textDecoration: 'none', color: '#007bff' }}>Profile</Link>
          </nav>
        </header>

        <main>
          <Routes>
            <Route path="/" element={<HomePage userPublicKey={userPublicKey} />} />
            <Route path="/profile" element={<ProfilePage userPublicKey={userPublicKey} />} />
            <Route path="*" element={<Navigate to="/" replace />} />
          </Routes>
        </main>
      </div>
    </Router>
  );
};

export default App;

// Filepath: src/App.tsx
// Author: Robert Kirkpatrick
// Generated by: Venice AI
// v11.0.1 - Updated routing to use LoginPage as the entry point
