// Filepath: src/HomePage.tsx
// Author: Robert Kirkpatrick
// Generated by: Venice AI
// v1.0.3 - Rebuilt from scratch to be a complete and functional component using EventForm and EventCard.

import React, { useRef } from 'react';
import { useAgoraData } from './hooks/useAgoraData';
import EventForm from './components/EventForm';
import EventCard from './components/EventCard';
import './App.css';

const HomePage: React.FC<{ userPublicKey: string }> = ({ userPublicKey }) => {
  const {
    events,
    hostProfiles,
    commenterProfiles,
    rsvps,
    comments,
    isLoading,
    isLoadingMore,
    hasMoreEvents,
    error,
    clearError,
    handleLoadMore,
    handleCreateEvent,
    handleToggleRSVP,
    handlePostComment,
    handleShareAsNote,
    handleShareEvent,
  } = useAgoraData(userPublicKey);

  const fileInputRef = useRef<HTMLInputElement>(null);

  const handleImageUpload = async (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (!file) return;
    const formData = new FormData();
    formData.append('file', file);
    try {
      const response = await fetch('https://nostr.build/api/v2/nip96/upload', {
        method: 'POST',
        body: formData,
      });
      if (!response.ok) throw new Error('Upload failed');
      const result = await response.json();
      if (result.nip96_event?.tags?.[0]?.[2]) {
        const imageUrl = result.nip96_event.tags[0][2];
        const urlInput = document.querySelector('input[name="image_url"]') as HTMLInputElement;
        if (urlInput) urlInput.value = imageUrl;
      } else {
        throw new Error('Could not retrieve image URL from response.');
      }
    } catch (err: any) {
      alert(`Image upload failed: ${err.message}`);
    }
  };

  if (isLoading) {
    return <div>Loading events...</div>;
  }

  return (
    <div>
      <h2>Upcoming Agora Meetups</h2>

      <EventForm onSubmit={handleCreateEvent} />

      <input
        type="file"
        ref={fileInputRef}
        onChange={handleImageUpload}
        accept="image/*"
        style={{ display: 'none' }}
      />
      <p style={{ textAlign: 'center', margin: '10px 0' }}>
        <button onClick={() => fileInputRef.current?.click()}>Upload Image for Event</button>
      </p>

      {error && (
        <div style={{ color: 'red', padding: '10px', border: '1px solid red', background: '#ffeeee' }}>
          Error: {error} <button onClick={clearError} style={{ marginLeft: '10px' }}>X</button>
        </div>
      )}

      <div className="meetup-list">
        {events.map(event => {
         //  const eventData = JSON.parse(event.content);
          const hostName = hostProfiles[event.pubkey]?.name || event.pubkey.substring(0, 8) + '...';
          const eventComments = comments[event.id] || [];
          const isAttending = rsvps[event.id]?.has(userPublicKey) || false;

          return (
            <EventCard
              key={event.id}
              event={event}
              hostName={hostName}
              isAttending={isAttending}
              comments={eventComments}
              commenterProfiles={commenterProfiles}
              onToggleRSVP={handleToggleRSVP}
              onPostComment={handlePostComment}
              onShareAsNote={handleShareAsNote}
              onShareEvent={handleShareEvent}
            />
          );
        })}
      </div>

      {hasMoreEvents && (
        <div style={{ textAlign: 'center', marginTop: '20px' }}>
          <button onClick={handleLoadMore} disabled={isLoadingMore}>
            {isLoadingMore ? 'Loading...' : 'Load More Events'}
          </button>
        </div>
      )}
    </div>
  );
};

export default HomePage;
