// Filepath: src/HomePage.tsx
// Author: Robert Kirkpatrick
// Generated by: Venice AI
// v15.8.0 - Updated event creation form to use a file input for images with a local preview. Upload functionality is a placeholder.

import React, { useState } from 'react';
import { DateTime } from 'luxon';
import { useAgoraData } from './hooks/useAgoraData';

// --- Main HomePage Component ---
// This component now serves as the primary UI layer. It consumes data and handler functions
// from the useAgoraData hook and is responsible for rendering the application view.
const HomePage: React.FC<{ userPublicKey: string }> = ({ userPublicKey }) => {
    // --- Import all state and handler functions from our custom hook ---
    const {
        events, hostProfiles, commenterProfiles, friends, rsvps, comments,
        isLoading, isLoadingMore, hasMoreEvents, error,
        clearError, handleLoadMore, handleCreateEvent, handleToggleRSVP,
        handlePostComment, handleShareAsNote, handleShareEvent
    } = useAgoraData(userPublicKey);

    // --- Local UI State (state that is purely for UI and not for Nostr) ---
    const [showCreateForm, setShowCreateForm] = useState(false);
    const [newEvent, setNewEvent] = useState({ name: '', location: '', startTime: '', description: '' }); // image_url removed
    const [selectedImageFile, setSelectedImageFile] = useState<File | null>(null);
    const [imagePreviewUrl, setImagePreviewUrl] = useState<string | null>(null);
    const [commentText, setCommentText] = useState<{ [eventId: string]: string }>({});
    const [commentImageUrl, setCommentImageUrl] = useState<{ [eventId: string]: string }>({});
    const [showCommentImageInput, setShowCommentImageInput] = useState<{ [eventId: string]: boolean }>({});
    
    // --- Event Handlers that call the hook's functions ---

    const onSubmitCreateEvent = async (e: React.FormEvent) => {
        e.preventDefault();
        
        let finalImageUrl = '';

        // If an image file is selected, upload it first
        if (selectedImageFile) {
            // --- Start NIP-96 Upload ---
            const uploadServer = 'https://nostr.build/api/v2/nip96/upload';
            const formData = new FormData();
            formData.append('file', selectedImageFile);

            try {
                // We use a placeholder for the authorization header.
                // A real implementation would sign a challenge for auth, but for now, we try without it.
                const response = await fetch(uploadServer, {
                    method: 'POST',
                    body: formData,
                });

                if (!response.ok) {
                    const errorText = await response.text();
                    throw new Error(`Upload failed: ${response.status} ${errorText}`);
                }

                const result = await response.json();
                
                // NIP-96 servers return the URL in a specific nested format
                if (result.nip94_event && result.nip94_event.tags) {
                    const urlTag = result.nip94_event.tags.find((tag: string[]) => tag[0] === 'url');
                    if (urlTag && urlTag[1]) {
                        finalImageUrl = urlTag[1];
                        console.log('Image uploaded successfully:', finalImageUrl);
                    } else {
                        throw new Error('Could not find image URL in upload response.');
                    }
                } else {
                    throw new Error('Upload response was not in the expected NIP-96 format.');
                }
            } catch (uploadError: any) {
                console.error('Image upload failed:', uploadError);
                alert(`Image upload failed: ${uploadError.message}. The event will be created without the image.`);
                // We continue without the image if the upload fails
            }
            // --- End NIP-96 Upload ---
        }

        // Create the event object, with the uploaded image URL (or an empty string if it failed)
        const eventToCreate = {
            ...newEvent,
            image_url: finalImageUrl,
        };

        // Call the hook's function to create the event on Nostr
        handleCreateEvent(e, eventToCreate);
    };

    const onImageFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
        const file = e.target.files?.[0];
        if (file) {
            setSelectedImageFile(file);
            const reader = new FileReader();
            reader.onloadend = () => {
                setImagePreviewUrl(reader.result as string);
            };
            reader.readAsDataURL(file);
        } else {
            setSelectedImageFile(null);
            setImagePreviewUrl(null);
        }
    };

    const onClickPostComment = (eventId: string) => {
        const text = commentText[eventId] || '';
        const imageUrl = commentImageUrl[eventId] || '';
        let finalContent = text.trim();
        if (imageUrl && imageUrl.trim()) {
            finalContent += `\n\n${imageUrl.trim()}`;
        }
        handlePostComment(eventId, finalContent);
    };

    // --- Render Helper Functions ---

    const getHostName = (pubkey: string) => { 
        const profile = hostProfiles[pubkey]; 
        return profile?.name || pubkey.substring(0, 8) + '...'; 
    };

    const getCommenterName = (pubkey: string) => { 
        const profile = commenterProfiles[pubkey] || hostProfiles[pubkey]; 
        return profile?.name || pubkey.substring(0, 8) + '...'; 
    };
    
    const renderContentWithImages = (text: string): (string | React.ReactElement)[] => {
        const urlRegex = /(https?:\/\/[^^\s]+)/g;
        const parts: (string | React.ReactElement)[] = [];
        let lastIndex = 0;
        let match;

        while ((match = urlRegex.exec(text)) !== null) {
            if (match.index > lastIndex) { 
                parts.push(text.substring(lastIndex, match.index)); 
            }
            const url = match[0];
            if (/\.(jpeg|jpg|gif|png|webp)(\?.*)?$/i.test(url)) { 
                parts.push(
                    <img 
                        key={url} 
                        src={url} 
                        alt="User embedded image" 
                        style={{ maxWidth: '100%', height: 'auto', borderRadius: '8px', marginTop: '10px', display: 'block' }} 
                    />
                ); 
            } else { 
                parts.push(url); 
            }
            lastIndex = urlRegex.lastIndex;
        }

        if (lastIndex < text.length) { 
            parts.push(text.substring(lastIndex)); 
        }

        return parts;
    };

    // --- Render Logic ---
    return (
        <div>
            {/* --- Error Display Banner --- */}
            {error && (
                <div style={{ backgroundColor: '#f8d7da', color: '#721c24', border: '1px solid #f5c6cb', padding: '15px', borderRadius: '8px', marginBottom: '20px', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                    <span>{error}</span>
                    <button onClick={clearError} style={{ background: 'none', border: 'none', color: '#721c24', fontSize: '1.5em', cursor: 'pointer', padding: '0', lineHeight: '1' }}>&times;</button>
                </div>
            )}

            <h2>Upcoming Agora Events</h2>
            <button onClick={() => setShowCreateForm(!showCreateForm)} style={{ marginBottom: '20px', padding: '10px 20px', cursor: 'pointer' }}>
                {showCreateForm ? 'Cancel' : 'Create New Event'}
            </button>
            {showCreateForm && (
                <form onSubmit={onSubmitCreateEvent} style={{ border: '1px solid #ccc', padding: '20px', borderRadius: '8px', marginBottom: '20px' }}>
                    <input placeholder="Event Name" value={newEvent.name} onChange={(e) => setNewEvent({ ...newEvent, name: e.target.value })} required style={{ display: 'block', width: '98%', marginBottom: '10px', padding: '10px' }} />
                    <input placeholder="Location" value={newEvent.location} onChange={(e) => setNewEvent({ ...newEvent, location: e.target.value })} required style={{ display: 'block', width: '98%', marginBottom: '10px', padding: '10px' }} />
                    <input type="datetime-local" value={newEvent.startTime} onChange={(e) => setNewEvent({ ...newEvent, startTime: e.target.value })} required style={{ display: 'block', width: '98%', marginBottom: '10px', padding: '10px' }} />
                    <textarea placeholder="Description" value={newEvent.description} onChange={(e) => setNewEvent({ ...newEvent, description: e.target.value })} rows={4} style={{ display: 'block', width: '98%', marginBottom: '10px', padding: '10px' }} />
                    
                    {/* --- New Image Input and Preview --- */}
                    <label htmlFor="image-upload" style={{ display: 'block', marginBottom: '5px', fontWeight: 'bold' }}>Event Image (optional)</label>
                    <input 
                        id="image-upload"
                        type="file" 
                        accept="image/*" 
                        onChange={onImageFileChange} 
                        style={{ display: 'block', width: '98%', marginBottom: '10px', padding: '8px', border: '1px solid #ccc', borderRadius: '4px' }}
                    />
                    {imagePreviewUrl && (
                        <div style={{ marginBottom: '10px' }}>
                            <p style={{ margin: '0 0 5px 0', fontSize: '0.9em', color: '#555' }}>Image Preview:</p>
                            <img src={imagePreviewUrl} alt="Event preview" style={{ maxWidth: '200px', maxHeight: '150px', objectFit: 'cover', borderRadius: '8px', border: '1px solid #ddd' }} />
                        </div>
                    )}

                    <button type="submit" style={{ padding: '10px 20px', cursor: 'pointer' }}>Share to Feed</button>
                </form>
            )}
            {isLoading ? (<p>Loading events...</p>) : (
                <div className="meetups-grid">
                    {events.length === 0 ? (<p>No upcoming events found. Be the first to create one!</p>) : (
                        events.map(event => {
                            const eventData = JSON.parse(event.content); 
                            const startTime = DateTime.fromISO(eventData.startTime); 
                            const eventRsvpsSet = rsvps[event.id] || new Set(); 
                            const eventRsvps = Array.from(eventRsvpsSet); 
                            const isHostFriend = friends.has(event.pubkey); 
                            const amIAttending = eventRsvpsSet.has(userPublicKey); 
                            const attendingFriends = eventRsvps.filter(rsvpPubkey => friends.has(rsvpPubkey) && rsvpPubkey !== userPublicKey); 
                            const isMyEvent = event.pubkey === userPublicKey; 
                            const eventComments = comments[event.id] || [];
                            
                            return (
                                <div key={event.id} className="meetup-card">
                                    {eventData.image_url && <img src={eventData.image_url} alt={eventData.name} className="event-image" />}
                                    <div className="card-content">
                                        <h3>{eventData.name}</h3>
                                        <p><strong>Where:</strong> {eventData.location}</p>
                                        <p><strong>When:</strong> {startTime.toLocaleString(DateTime.DATETIME_FULL)}</p>
                                        <p>{eventData.description}</p>
                                    </div>
                                    <div className="card-footer">
                                        <div>
                                            <span>Hosted by: {getHostName(event.pubkey)}</span>
                                            {isHostFriend && !isMyEvent && <span style={{ color: '#28a745', fontWeight: 'bold', marginLeft: '10px' }}>🤝 Friend</span>}
                                        </div>
                                    </div>
                                    <div className="card-footer" style={{ borderTop: '1px solid #eee', paddingTop: '10px' }}>
                                        <div>
                                            <span>Attending ({eventRsvps.length})</span>
                                            {amIAttending && !isMyEvent && <span style={{ color: '#007bff', fontWeight: 'bold', marginLeft: '10px' }}>✓ You're Going</span>}
                                            {attendingFriends.length > 0 && <span style={{ color: '#28a745', fontWeight: 'bold', marginLeft: '10px' }}>🤝 {attendingFriends.length} Friend(s)</span>}
                                        </div>
                                        {isMyEvent ? (
                                            <div>
                                                <span style={{ color: '#6c757d', fontWeight: 'bold', marginRight: '10px' }}>Hosting</span>
                                                <button onClick={() => handleShareAsNote(event)} style={{ padding: '5px 10px', fontSize: '0.9em', cursor: 'pointer', marginRight: '5px' }}>Share as Note</button>
                                                <button onClick={() => handleShareEvent(event)} style={{ padding: '5px 10px', fontSize: '0.9em', cursor: 'pointer' }}>Share Event</button>
                                            </div>
                                        ) : (<button onClick={() => handleToggleRSVP(event.id)} style={{ padding: '5px 10px', fontSize: '0.9em', cursor: 'pointer' }}>{amIAttending ? 'Cancel RSVP' : 'RSVP'}</button>)}
                                    </div>
                                    <div className="card-footer" style={{ borderTop: '1px solid #eee', paddingTop: '10px', flexDirection: 'column', alignItems: 'flex-start' }}>
                                        <h4 style={{ margin: '0 0 10px 0', width: '100%' }}>Comments ({eventComments.length})</h4>
                                        <div style={{ width: '100%', maxHeight: '200px', overflowY: 'auto', marginBottom: '10px' }}>
                                            {eventComments.length === 0 && <p style={{ fontSize: '0.9em', color: '#666' }}>No comments yet.</p>}
                                            {eventComments.map(comment => {
                                                const commenterName = getCommenterName(comment.pubkey); 
                                                const isCommenterFriend = friends.has(comment.pubkey);
                                                
                                                return (
                                                    <div key={comment.id} style={{ borderBottom: '1px solid #f0f0f0', paddingBottom: '8px', marginBottom: '8px' }}>
                                                        <strong>{commenterName}</strong>
                                                        {isCommenterFriend && <span style={{ color: '#28a745', fontWeight: 'bold', marginLeft: '5px' }}>🤝</span>}
                                                        <span style={{ float: 'right', fontSize: '0.8em', color: '#999' }}>{DateTime.fromSeconds(comment.created_at).toRelative()}</span>
                                                        <p style={{ margin: '5px 0 0 0', fontSize: '0.9em', whiteSpace: 'pre-wrap' }}>{renderContentWithImages(comment.content)}</p>
                                                    </div>
                                                );
                                            })}
                                        </div>
                                        <div style={{ width: '100%' }}>
                                            <textarea
                                                placeholder="Add a comment..."
                                                value={commentText[event.id] || ''}
                                                onChange={(e) => setCommentText({ ...commentText, [event.id]: e.target.value })}
                                                rows={3}
                                                style={{ width: '100%', marginBottom: '10px', padding: '8px', boxSizing: 'border-box', resize: 'vertical' }}
                                            />
                                            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '10px' }}>
                                                <button
                                                    onClick={() => setShowCommentImageInput(prev => ({ ...prev, [event.id]: !prev[event.id] }))}
                                                    style={{ padding: '5px 10px', cursor: 'pointer', fontSize: '0.9em' }}
                                                >
                                                    {showCommentImageInput[event.id] ? 'Cancel Image' : '+ Add Image'}
                                                </button>
                                            </div>
                                            {showCommentImageInput[event.id] && (
                                                <input
                                                    type="url"
                                                    placeholder="Image URL"
                                                    value={commentImageUrl[event.id] || ''}
                                                    onChange={(e) => setCommentImageUrl({ ...commentImageUrl, [event.id]: e.target.value })}
                                                    style={{ display: 'block', width: '100%', marginBottom: '10px', padding: '8px', boxSizing: 'border-box' }}
                                                />
                                            )}
                                            <div style={{ display: 'flex', justifyContent: 'flex-end' }}>
                                                <button onClick={() => onClickPostComment(event.id)} style={{ padding: '8px 12px', cursor: 'pointer' }}>Post</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            );
                        })
                    )}
                </div>
            )}
            {!isLoading && hasMoreEvents && events.length > 0 && (
                <div style={{ textAlign: 'center', marginTop: '30px' }}>
                    <button onClick={handleLoadMore} disabled={isLoadingMore} style={{ padding: '10px 20px', cursor: isLoadingMore ? 'not-allowed' : 'pointer', opacity: isLoadingMore ? 0.6 : 1 }}>
                        {isLoadingMore ? 'Loading...' : 'Load More'}
                    </button>
                </div>
            )}
        </div>
    );
};

export default HomePage;

// --- End of File ---
// Filepath: src/HomePage.tsx
// Version: v15.8.0
