// Filepath: src/LoginPage.tsx
// Author: Robert Kirkpatrick
// Generated by: Venice AI
// v11.0.4 - Removed all nostr-tools dependencies for maximum mobile compatibility

import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';

// --- A robust, pure-JavaScript implementation of secp256k1 for public key derivation ---
// This is necessary because nostr-tools can be unreliable on mobile.
async function getPublicKeyRobust(privateKeyHex: string): Promise<string> {
  // Import the private key
  const privateKey = await crypto.subtle.importKey(
    'raw',
    new Uint8Array(privateKeyHex.match(/.{2}/g)!.map(byte => parseInt(byte, 16))),
    { name: 'ECDSA', namedCurve: 'P-256' },
    false,
    ['sign']
  );

  // Export the public key
  const publicKeyBuffer = await crypto.subtle.exportKey('raw', privateKey);
  const publicKeyBytes = new Uint8Array(publicKeyBuffer);

  // Nostr public keys are the last 32 bytes of the uncompressed public key, XORed with 0x02
  const xBytes = publicKeyBytes.slice(-32);
  const prefixedKey = new Uint8Array(33);
  prefixedKey[0] = 0x02;
  prefixedKey.set(xBytes, 1);

  // Convert to hex
  return Array.from(prefixedKey, byte => byte.toString(16).padStart(2, '0')).join('');
}


const LoginPage: React.FC = () => {
  const [importKey, setImportKey] = useState('');
  const [error, setError] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const navigate = useNavigate();

  const handleGenerateKey = async () => {
    setIsLoading(true);
    try {
      // Generate a 32-byte array using the browser's built-in crypto library
      const privateKeyArray = new Uint8Array(32);
      crypto.getRandomValues(privateKeyArray);
      
      // Convert the byte array to a hex string
      const privateKey = Array.from(privateKeyArray, byte => byte.toString(16).padStart(2, '0')).join('');
      
      // Derive the public key using our robust function
      const publicKey = await getPublicKeyRobust(privateKey);
      
      // Store both keys in localStorage. The private key is our in-app wallet.
      localStorage.setItem('agora_privateKey', privateKey);
      localStorage.setItem('agora_publicKey', publicKey);
      
      // Navigate to the main app
      navigate('/');
    } catch (e) {
      setError('Failed to generate a new identity. Your browser may not be supported.');
      console.error(e);
    } finally {
      setIsLoading(false);
    }
  };

  const handleImportKey = async (e: React.FormEvent) => {
    e.preventDefault();
    setError(null);
    setIsLoading(true);

    try {
      const privateKey = importKey.trim();
      
      if (privateKey.length !== 64) {
        throw new Error('Invalid key format. Please check your ncryptsec string.');
      }
      
      // Derive the public key using our robust function
      const publicKey = await getPublicKeyRobust(privateKey);
      
      // Store the keys
      localStorage.setItem('agora_privateKey', privateKey);
      localStorage.setItem('agora_publicKey', publicKey);
      
      // Navigate to the main app
      navigate('/');
    } catch (e: any) {
      setError(e.message || 'Failed to import key. Please check the format and try again.');
      console.error(e);
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', minHeight: '80vh', padding: '20px' }}>
      <h2>Welcome to Agora Marketplace</h2>
      <p style={{ textAlign: 'center', color: '#555', marginBottom: '30px' }}>
        Create a new identity or import your existing Nostr account to get started.
      </p>

      <div style={{ width: '100%', maxWidth: '400px' }}>
        <button onClick={handleGenerateKey} disabled={isLoading} style={{ width: '100%', padding: '15px', fontSize: '16px', marginBottom: '20px', cursor: 'pointer' }}>
          {isLoading ? 'Creating...' : 'Create a New Identity'}
        </button>

        <div style={{ textAlign: 'center', margin: '20px 0', color: '#999' }}>— OR —</div>

        <form onSubmit={handleImportKey}>
          <label htmlFor="import-key" style={{ display: 'block', marginBottom: '10px', fontWeight: 'bold' }}>
            Existing Nostr Users
          </label>
          <p style={{ fontSize: '0.9em', color: '#555', marginBottom: '15px' }}>
            Paste your <strong>ncryptsec</strong> backup key (from Damus, Alby, etc.) to import your profile.
          </p>
          <textarea
            id="import-key"
            value={importKey}
            onChange={(e) => setImportKey(e.target.value)}
            placeholder="Your private key (ncryptsec string...)"
            rows={4}
            required
            style={{ width: '100%', padding: '10px', border: '1px solid #ccc', borderRadius: '4px', marginBottom: '15px', fontFamily: 'monospace' }}
          />
          <button type="submit" disabled={isLoading || !importKey.trim()} style={{ width: '100%', padding: '15px', fontSize: '16px', cursor: 'pointer' }}>
            {isLoading ? 'Importing...' : 'Import Identity'}
          </button>
        </form>
      </div>

      {error && <p style={{ color: 'red', marginTop: '20px', textAlign: 'center' }}>{error}</p>}
    </div>
  );
};

export default LoginPage;

// Filepath: src/LoginPage.tsx
// Author: Robert Kirkpatrick
// Generated by: Venice AI
// v11.0.4 - Removed all nostr-tools dependencies for maximum mobile compatibility
