// Filepath: src/ProfilePage.tsx
// Author: Robert Kirkpatrick
// Generated by: Venice AI
// v12.0.1 - Fetch own profile from relays for robustness

import React, { useState, useEffect } from 'react';
import * as QRCode from 'qrcode';
import * as nostrTools from 'nostr-tools';

// --- Main ProfilePage Component ---
const ProfilePage: React.FC<{ userPublicKey: string }> = ({ userPublicKey }) => {
  const [profileName, setProfileName] = useState('');
  const [profileAbout, setProfileAbout] = useState('');
  const [qrCodeUrl, setQrCodeUrl] = useState<string>('');
  const [isSaving, setIsSaving] = useState(false);
  const [saveStatus, setSaveStatus] = useState<string | null>(null);
  
  const RELAYS = ['wss://relay.damus.io', 'wss://nos.lol', 'wss://relay.snort.social'];

  // --- Load QR Code and Profile Data from Relays ---
  useEffect(() => {
    const loadProfile = async () => {
      const url = await QRCode.toDataURL(userPublicKey, { width: 200 });
      setQrCodeUrl(url);
      await fetchProfileFromRelays(userPublicKey);
    };
    loadProfile();
  }, [userPublicKey]);

  // --- NEW: Fetch existing profile from relays ---
  const fetchProfileFromRelays = async (pubkey: string) => {
    for (const relayUrl of RELAYS) {
      try {
        await new Promise<void>((resolve, reject) => {
          const socket = new WebSocket(relayUrl);
          socket.onopen = () => {
            const subscription = JSON.stringify(["REQ", "my-profile", { kinds: [0], authors: [pubkey], limit: 1 }]);
            socket.send(subscription);
          };
          socket.onmessage = (msg) => {
            const data = JSON.parse(msg.data);
            if (data[0] === 'EVENT' && data[2] && data[2].kind === 0) {
              try {
                const profileData = JSON.parse(data[2].content);
                setProfileName(profileData.name || '');
                setProfileAbout(profileData.about || '');
                socket.close();
                resolve(); // Found it, stop looking
              } catch (e) {
                console.warn("Could not parse profile content from relay.");
              }
            }
            if (data[0] === 'EOSE') {
              socket.close();
              resolve(); // End of events, move to next relay
            }
          };
          socket.onerror = () => {
            socket.close();
            reject();
          };
        });
        break; // If successful, no need to try other relays
      } catch (e) {
        console.warn(`Could not fetch profile from ${relayUrl}, trying next...`);
      }
    }
  };
  
  // --- Handle saving the profile (Updated for Robust Signing) ---
  const handleSaveProfile = async (e: React.FormEvent) => {
    e.preventDefault();
    const storedPrivateKey = localStorage.getItem('agora_privateKey');

    let signedEvent;
    const profileContent = { name: profileName, about: profileAbout };

    if (storedPrivateKey) {
      const eventPayload = {
        pubkey: userPublicKey,
        created_at: Math.floor(Date.now() / 1000),
        kind: 0,
        tags: [],
        content: JSON.stringify(profileContent),
      };
      signedEvent = nostrTools.finalizeEvent(eventPayload, storedPrivateKey);
    } else if (window.nostr) {
      setSaveStatus('Waiting for you to approve the signature in your extension...');
      const eventPayload = {
        pubkey: userPublicKey,
        created_at: Math.floor(Date.now() / 1000),
        kind: 0,
        tags: [],
        content: JSON.stringify(profileContent),
      };
      signedEvent = await window.nostr.signEvent(eventPayload);
    } else {
      setSaveStatus('Error: No signing method found. Please log in again.');
      return;
    }

    setIsSaving(true);
    setSaveStatus('Broadcasting to relays...');
    let successCount = 0;
    for (const relayUrl of RELAYS) {
      try {
        await new Promise<void>((resolve, reject) => {
          const socket = new WebSocket(relayUrl);
          const message = JSON.stringify(["EVENT", signedEvent]);
          socket.onopen = () => {
            socket.send(message);
            setTimeout(() => {
              socket.close();
              resolve();
            }, 500);
          };
          socket.onerror = reject;
        });
        successCount++;
      } catch (err) {
        console.warn(`Failed to post to ${relayUrl}`);
      }
    }
    setSaveStatus(`Success! Profile updated on ${successCount}/${RELAYS.length} relays.`);
    setIsSaving(false);
  };

  return (
    <div>
      <h2>Your Nostr Profile</h2>
      <p style={{ color: '#555' }}>This information is public and will be associated with your events.</p>
      
      <div style={{ display: 'flex', gap: '40px', flexWrap: 'wrap' }}>
        <div style={{ flex: '1', minWidth: '300px' }}>
          <h3>Profile Details</h3>
          <form onSubmit={handleSaveProfile}>
            <div style={{ marginBottom: '15px' }}>
              <label htmlFor="name" style={{ display: 'block', marginBottom: '5px', fontWeight: 'bold' }}>Display Name</label>
              <input
                id="name"
                type="text"
                value={profileName}
                onChange={(e) => setProfileName(e.target.value)}
                style={{ width: '100%', padding: '10px', border: '1px solid #ccc', borderRadius: '4px' }}
              />
            </div>
            <div style={{ marginBottom: '15px' }}>
              <label htmlFor="about" style={{ display: 'block', marginBottom: '5px', fontWeight: 'bold' }}>About</label>
              <textarea
                id="about"
                value={profileAbout}
                onChange={(e) => setProfileAbout(e.target.value)}
                rows={4}
                style={{ width: '100%', padding: '10px', border: '1px solid #ccc', borderRadius: '4px', resize: 'vertical' }}
              />
            </div>
            <button type="submit" disabled={isSaving} style={{ padding: '10px 20px', border: 'none', borderRadius: '4px', backgroundColor: '#007bff', color: 'white', cursor: 'pointer' }}>
              {isSaving ? 'Saving...' : 'Save Profile'}
            </button>
            {saveStatus && <p style={{ marginTop: '10px' }}>{saveStatus}</p>}
          </form>
        </div>

        <div style={{ flex: '0 0 auto', textAlign: 'center' }}>
          <h3>Your Public Key (QR Code)</h3>
          <p style={{ fontSize: '0.8em', color: '#555', wordBreak: 'break-all' }}>{userPublicKey}</p>
          {qrCodeUrl && <img src={qrCodeUrl} alt="Public Key QR Code" style={{ border: '1px solid #ddd', padding: '10px', backgroundColor: '#fff' }} />}
        </div>
      </div>
    </div>
  );
};

export default ProfilePage;

// Filepath: src/ProfilePage.tsx
// Author: Robert Kirkpatrick
// Generated by: Venice AI
// v12.0.1 - Fetch own profile from relays for robustness
