// Filepath: src/types.d.ts
// Author: Robert Kirkpatrick
// Generated by: Venice AI
// v1.0.0 - Global type declarations for the project.

declare global {
  interface Window {
    nostr?: {
      getPublicKey: () => Promise<string>;
      signEvent: (event: any) => Promise<any>;
    };
  }
}

export {}; // This makes the file a module, which is required for augmenting global scopes.
